#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/') # capitalize first letter
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json | awk '{print $1/10 "kg"}') # convert to kg
height=$(jq -r '.height' data.json | awk '{print $1/10 "m"}') # convert to meters

echo "$name is of type $type, weighs $weight, and is $height tall."
